/*
 * Copyright (C) 2020 Vojtěch Perník <v.pernik@centrum.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cz.pervoj.lttedit;

import cz.pervoj.lttedit.classes.TranslationController;
import cz.pervoj.lttedit.classes.TranslationParser;
import cz.pervoj.lttlib.LTTGetter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Vojtěch Perník <v.pernik@centrum.cz>
 */
public class NewTranslationJDialog extends javax.swing.JDialog {
    private JFileChooser jfc = new JFileChooser();
    private File pattern;
    private File translation;
    private TranslationController translations;
    private boolean created = false;
    private LTTGetter ltt;

    /**
     * Creates new form NewTranslationJDialog
     */
    public NewTranslationJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            ltt = LTTInstancer.getInstance();
        } catch (Exception e) {
            e.printStackTrace();
        }
        setLocationRelativeTo(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        codeJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        authorJTextField = new javax.swing.JTextField();
        selectJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fileJLabel = new javax.swing.JLabel();
        createJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ltt.getText("create new translation"));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel1.setText(ltt.getText("language name:"));

        nameJTextField.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        codeJTextField.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel2.setText(ltt.getText("language code:"));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel3.setText(ltt.getText("author:"));

        authorJTextField.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        selectJButton.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        selectJButton.setText(ltt.getText("select"));
        selectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel4.setText(ltt.getText("pattern file:"));

        fileJLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        fileJLabel.setText(ltt.getText("no file selected"));

        createJButton.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        createJButton.setText(ltt.getText("create"));
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJTextField)
                            .addComponent(codeJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(authorJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectJButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectJButton)
                    .addComponent(jLabel4)
                    .addComponent(fileJLabel))
                .addGap(18, 18, 18)
                .addComponent(createJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectJButtonActionPerformed
        jfc.setFileFilter(new FileNameExtensionFilter(ltt.getText("lttp files"), "lttp"));
        jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = jfc.showDialog(this, ltt.getText("select"));
        if (result == JFileChooser.APPROVE_OPTION) {
            pattern = jfc.getSelectedFile();
            translation = new File(pattern.getParent() + "/" + codeJTextField.getText() + ".ltt");
            fileJLabel.setText(pattern.getName());
            
            if (translation.exists()) {
                JOptionPane.showMessageDialog(this, ltt.getText("translation already exists"), ltt.getText("warning"), JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_selectJButtonActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        if (nameJTextField.getText() == "" || codeJTextField.getText() == "" || authorJTextField.getText() == "" || pattern == null || translation == null) {
            JOptionPane.showMessageDialog(this, ltt.getText("all fields are not filled"), ltt.getText("error"), JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                translations = TranslationParser.parseFile(pattern, translation, nameJTextField.getText(), codeJTextField.getText(), authorJTextField.getText());
                created = true;
                dispose();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage(), ltt.getText("error"), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_createJButtonActionPerformed

    public TranslationController getTranslationController() {
        return translations;
    }
    
    public File getFile() {
        return translation;
    }
    
    public boolean isCreated() {
        return created;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorJTextField;
    private javax.swing.JTextField codeJTextField;
    private javax.swing.JButton createJButton;
    private javax.swing.JLabel fileJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton selectJButton;
    // End of variables declaration//GEN-END:variables
}
